In [29]:
import pandas as pd

In [31]:
pd.__version__

'1.2.4'

In [32]:
ser = pd.Series([0.25, 0.5, 0.75, 1]) # constructor method: 객체를 생성하는 메서드
print(ser)
print(ser.shape)

print(ser.index)


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
(4,)
RangeIndex(start=0, stop=4, step=1)


In [33]:
ser = pd.Series([0.25, 0.5, 0.75, 1], index=['a', 'b', 'c', 'd'])
print(ser)

print(ser['b'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


In [34]:
dict = {'a': 1 , 2: 'two', 'third': True} # key: value
print(dict)

{'a': 1, 2: 'two', 'third': True}


In [35]:
population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}

population = pd.Series(population_dict)
print(population, '\n')
print(population['Texas'])

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64 

26448193


In [36]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [41]:
df = pd.DataFrame({'population': population, 'area': area})
print(df)

print(df.index)
print(df.columns, '\n')

# area = df['area']
# print(area)

import numpy as np

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object') 



In [38]:
arr = np.random.rand(3, 2)
print(arr, '\n')

df = pd.DataFrame(arr, columns=['foo', 'bar'], index=['2021-10-13', '2021-10-14', '2021-10-15'])
print(df)

[[0.28922991 0.5094281 ]
 [0.20114631 0.6233484 ]
 [0.40529322 0.745273  ]] 

                 foo       bar
2021-10-13  0.289230  0.509428
2021-10-14  0.201146  0.623348
2021-10-15  0.405293  0.745273


In [39]:
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(ser, '\n')

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64 



In [52]:
df['density'] = df['population'] / df['area']

print(df)

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763


In [56]:
print(df.loc['New York'])

population    1.965113e+07
area          1.412970e+05
density       1.390767e+02
Name: New York, dtype: float64


In [60]:
print(df.values, '\n')
print(df.T, '\n')

print(df.iloc[:3, :2], '\n')
print(df.loc[df.density > 100, ['population', 'density']], '\n')

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01   

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

          population     density
New York    19651127  139.076746
Florida     19552860  114.806121 

