In [1]:
import numpy as np

In [13]:
"""
Computing reciprocals in loops
"""

# Function for computing reciprocals using looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

np.random.seed(0)
values = np.random.randint(1, 10, size=5)
print(values)

output = compute_reciprocals(values)
print(output)

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [18]:
"""
Comparison: Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1, 100, size=1000000)
print(big_array)

# Looping on a big array

%timeit compute_reciprocals(big_array)

[79 11 71 ... 58 51 56]
1.56 s ± 5.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
# Vectorized operations

%timeit 1 / big_array

2.63 ms ± 41 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1 -= 2
print(arr1)

arr3 = arr1 + arr2
print(arr3, "\n")

arr4 = np.random.randint(10, size=(3, 5))
print(arr4, "\n")

print(arr4 ** 2)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7] 

[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]] 

[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [36]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2, -1, 0 ,1, 2])
np.abs(x)

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[5. 5. 2. 1.]


In [43]:
"""
UFuncs: Trigonmetric Functions
"""

theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [59]:
"""
UFuncs: Aggregation
"""

x = np.arange(1, 5)
print(x, "\n")
aggr = np.add.reduce(x)
print(aggr,"\n")

aggr = np.multiply.reduce(x)
print(aggr, "\n")

accum = np.add.accumulate(x)
print(accum, "\n")

accum = np.multiply.accumulate(x)
print(accum, "\n")

[1 2 3 4] 

10 

24 

[ 1  3  6 10] 

[ 1  2  6 24] 



In [82]:
# Summing the Values in an Array
np.random.seed(3)

arr = np.random.rand(1000000)
print(arr)

print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [87]:
%timeit sum(arr) # python style

63.6 ms ± 736 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [90]:
%timeit np.sum(arr)

749 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [197]:
#other Aggr. functions

print(arr)
print("max =" ,np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))

print(np.any(arr>1))
print(np.all(arr>0))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.500422198970153
median = 0.5005659265960778
percentile = 0.9001765340710965
False
True


In [201]:
# Multi dimesional aggregates

np.random.seed(5)
arr = np.random.randint(10, size=(3, 4))
print(arr, "\n")

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]] 

[12 14 17  8]
[15 28  8]
